# Generated by Django 4.2.25 on 2025-10-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parentcodeapp', '0004_alter_comment_author_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
