# Generated by Django 4.2.25 on 2025-10-13 10:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parentcodeapp', '0006_contactform_myprofile_jobpost_bookmarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
